---
 # run this PB with;
 # ansible-playbook pb_exp_1_ds.yml -e "datastore_name=RedDotAC1MikeWasHere"

- name: expand
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./inventory/group_vars/purefa.yml
  tasks:
  - name: Expand the partition number 1 in the datastore capacity using free all capacity up to
    delegate_to: localhost
    community.vmware.vmware_host_datastore_resize:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vmware_validate_certs }}"
      esxi_hostname: "{{ esxi_hostname }}"
      datastore: "{{ datastore_name }}"
      expand:
        partition_number: 1
        resize_gb: all
