---
- name: Create a DEMO VM
  hosts: localhost
  connection: local
  gather_facts: true
  collections:
  - community.vmware
  vars_files:
    - vars.yaml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: "{{ vm_template }}"
      datastore: "{{ migration_datastore_name }}"
      datacenter: "{{ datacenter }}"
      folder: "{{ vm_folder }}"
      state: poweredon
      wait_for_ip_address: no
      customization_spec: "{{ customization_spec }}"