- hosts: purefa
  gather_facts: false
  tasks:
    - name: Update Banner
      delegate_to: localhost
      purestorage.flasharray.purefa_banner:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ pure_api_token }}"
        banner: "{{ banner }}"
