- hosts: localhost
  tasks:
 # run this FIRST to delete the VMFS Datastore and asscioated volume;
 # for: purefa[0]
 # ansible-playbook -i inventory ./del/pb_del_1_datastore.yml -e "array=10.0.0.1 datastore_name=RedDotAC1MikeWasHere hg_name=mgmt-esxi"
 # for: purefa[1]
 # ansible-playbook -i inventory ./del/pb_del_1_datastore.yml -e "array=10.0.0.2 datastore_name=RedDotAC2MikeWasHere hg_name=mgmt-esxi"
- name: Deletes Hosts and Host Groups
  import_playbook: ./del/pb_del_2_host.yml
- name: Remove VIFs and Subnets
  import_playbook: ./del/pb_del_3_subnet.yml
- name: Return Flash Array to normal login page
  import_playbook: ./del/pb_del_4_config.yml
