---
 # run this PB with;
 # for: purefa[0] increase the Array Volume to 6TB and the asscioated VMFS Datastore
 # ansible-playbook -i inventory pb_exp_1_datastore.yml -e "array=10.226.224.122 datastore_name=RedDotAC1MikeWasHere datastore_size=6T"
 
 # for: purefa[1] increase the Array Volume to 4TB and the asscioated VMFS Datastore
 # ansible-playbook -i inventory pb_exp_1_datastore.yml -e "array=10.226.224.132 datastore_name=RedDotAC2MikeWasHere datastore_size=4T"

- hosts: "{{ array }}"
  gather_facts: false
  tasks:
    - name: Extend Volume
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ pure_api_token }}"
        name: "{{ datastore_name }}"
        size: "{{ datastore_size }}"

    - name: Rescan VMWare HBA
      delegate_to: localhost
      vmware_host_scanhba:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vmware_validate_certs }}"
        refresh_storage: true
        esxi_hostname: '{{ esxi_hostname }}'
        #cluster_name: "{{ vmware_cluster_name }}"
#      register: vmware_rescan_info

# PR 915
    - name: Expand Datastore
      delegate_to: localhost
      vmware_host_datastore:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vmware_validate_certs }}"
        datastore_name: "{{ datastore_name }}"
        esxi_hostname: '{{ esxi_hostname }}'
        auto_expand: True
        #esxi_hostname: "{{ (vmware_rescan_info.result | dict2items)[0].key }}"  # Grab the First host in the cluster to configure the Datastore
